# Generated by Django 3.1.1 on 2021-04-26 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='unique_file',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
