# Generated by Django 3.2 on 2021-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='unique_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
