# Generated by Django 3.1.1 on 2021-06-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_unique_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
